### ISSUE TITLE
Pretrained model weights

### ISSUE THREAD

**Issue by ZhangHanbo** [lyttttt3333/Broadcast_Support_Relation#2]
Hi there

Thanks for your great work on support relation prediction. Really impressive.

I am wondering if you plan to release pretrained model weights for inference? 

Look forward to hearing from you.

**Comment by lyttttt3333** [comment]
Hi! Thank you very much for your interest in our project! I am really sorry for missing your message yesterday.
Of course we will release our model weights, but I have to apologize for the potential delay because currently our authors are occupied by NeurIPS rebuttal. We will fasten this process to the maximum extent and release it as soon as possible, in a week after the rebuttal, as well as a part of corresponding data. Thanks again for your interest and understanding!

**Comment by warshallrho** [comment]
Yitong @lyttttt3333 has released the model. Welcome to have a try!
